apiVersion: v1
kind: Pod
metadata:
  name: kplabs-pod
spec:
  containers:
  - name: kplabs-container
    image: nginx
    resources:
      requests:
        memory: "64000Mi"
        cpu: "0.5"
      limits:
        memory: "128000Mi"
        cpu: "1"