apiVersion: v1
kind: Pod
metadata:
  name: kplabs-pod-create
spec:
  containers:
  - name: kplabs-container
    image: nginx
    resources:
      requests:
        memory: "64Mi"
      limits:
        memory: "12800Mi"