apiVersion: v1
kind: Pod
metadata:
  name: ambassador-example
spec:
  containers:
  - name: myapp
    image: nginx
    ports:
      - containerPort: 80
  - name: ambassador
    image: alpine
    command:
      - /bin/sh
      - -c
      - |
        apk add --no-cache socat &&         # Proxy traffic from localhost:8080 to external-service:80
        socat TCP-LISTEN:8080,fork TCP:external-service.default.svc.cluster.local:80
    ports:
      - containerPort: 8080
  - name: adapter
    image: curlimages/curl
    command:
      - /bin/sh
      - -c
      - |
        # Transform data: fetch from ambassador, modify, then serve
        while true; do
          curl -s http://localhost:8080 | sed 's/nginx/NGINX_ADAPTED/' > /tmp/output.html;
          sleep 5;
        done
    volumeMounts:
      - name: data
        mountPath: /tmp
  volumes:
    - name: data
      emptyDir: {}
