apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: backend # must have a label to automate the process
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend # Must match the label
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80