apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods
  namespace: default
subjects:
- kind: User
  name: system:serviceaccount:default:external # account name (Possible get from Forbidden Error request to API)
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pod-reader # The name of the Role.yaml
  apiGroup: rbac.authorization.k8s.io