apiVersion: v1
kind: Pod
metadata:
  name: pod-hdd #(manually adding pods)-pod
spec:
  containers:
    - name: pod-hdd #(manually adding pods)-pod
      image: nginx
  nodeSelector:
    disk: hdd

# The Node must be with the apropriete label to be assigned to 
# (In this case disk=hdd)
