apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: vlad-csr
spec:
  groups:
  - system:authenticated
  request: ADD-YOUR-CSR-HERE # after it has been base64 decoded
  signerName: kubernetes.io/kube-apiserver-client
  usages:
  - digital signature
  - key encipherment
  - client auth