apiVersion: v1
kind: Endpoints
metadata:
  name: kplabs-service #must match the service(manually adding pods) name
subsets:
  - addresses:
      - ip: 10.244.0.212
      - ip: 10.244.0.129 # must be ip of the 1-backend pods
    ports:
      - port: 80