apiVersion: v1
kind: Pod
metadata:
  labels:
    env: dev
  name: pod-1
spec:
  containers:
    - name: nginx-container-1
      image: nginx

---
apiVersion: v1
kind: Pod
metadata:
  labels:
    env: stage
  name: pod-2
spec:
  containers:
    - name: nginx-container-2
      image: nginx

---
apiVersion: v1
kind: Pod
metadata:
  labels:
    env: prod
  name: pod-3
spec:
  containers:
    - name: nginx-container-3
      image: nginx