apiVersion: v1
kind: Service
metadata:
  labels:
    app: nodeport-service
  name: nodeport-service
spec:
  ports:
  - name: 5678-80
    port: 5678
    protocol: TCP
    targetPort: 80
  selector:
    app: nodeport-service
  type: NodePort
