apiVersion: v1
kind: Pod
metadata:
  name: adapter-example
spec:
  containers:
  - name: main-app
    image: nginx
    ports:
      - containerPort: 80
    volumeMounts:
      - name: shared-data
        mountPath: /usr/share/nginx/html
  - name: adapter
    image: busybox
    command:
      - /bin/sh
      - -c
      - |
        # Example adapter: fetch main-app content, transform, and write back
        while true; do
          if [ -f /data/index.html ]; then
            sed 's/Welcome/Welcome to Adapted NGINX/' /data/index.html > /data/index.html.tmp
            mv /data/index.html.tmp /data/index.html
          fi
          sleep 10
        done
    volumeMounts:
      - name: shared-data
        mountPath: /data
  volumes:
    - name: shared-data
      emptyDir: {}
